version: "2"
run:
  go: "1.24"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - importas
    - ireturn
    - lll
    - makezero
    - misspell
    - nakedret
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usetesting
    - varnamelen
    - wastedassign
    - wsl_v5
  settings:
    funlen:
      lines: 175
      statements: 85
    gocognit:
      min-complexity: 36
    lll:
      line-length: 135
    revive:
      rules:
        - name: indent-error-flow
        - name: increment-decrement
    staticcheck:
      checks:
        - -ST1001
        - all
      dot-import-whitelist:
        - github.com/onsi/gomega
        - github.com/onsi/ginkgo/v2
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      disable:
        - append
        - assign
        - err
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - test/tools.go
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - test/tools.go
      - third_party$
      - builtin$
      - examples$
