---
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: performance
spec:
  cpu:
    isolated: 10-15
    offlined: 4-9
    reserved: 0-3
  hugepages:
    defaultHugepagesSize: 1G
    pages:
      - size: 1G
        count: 5
      - size: 2M
        count: 10
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/master: ""
  nodeSelector:
    node-role.kubernetes.io/master: ""
  realTimeKernel:
    enabled: true
