---
name: Makefile CI

'on':
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      SHELL: /bin/bash

    steps:
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.5

      - uses: actions/checkout@v3
      - uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: README.md
      - uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: vendor
      - uses: mfinelli/setup-shfmt@v2
      - run: shfmt -d scripts/*.sh
      - uses: crate-ci/typos@master
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/*.yml
          strict: true

      - name: Run lint
        run: make lint

      - name: Run Unit Tests
        run: make unit-tests

      - name: Install ginkgo
        run: make install-ginkgo

      - name: Compile test suites
        run: ginkgo build -r ./tests
